# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anasayfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 110, 225, 166))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.kullaniciAdiLabel = QtWidgets.QLabel(self.layoutWidget)
        self.kullaniciAdiLabel.setObjectName("kullaniciAdiLabel")
        self.verticalLayout.addWidget(self.kullaniciAdiLabel)
        self.sifreLabel = QtWidgets.QLabel(self.layoutWidget)
        self.sifreLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sifreLabel.setObjectName("sifreLabel")
        self.verticalLayout.addWidget(self.sifreLabel)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.kullaniciAdiLne = QtWidgets.QLineEdit(self.layoutWidget)
        self.kullaniciAdiLne.setObjectName("kullaniciAdiLne")
        self.verticalLayout_2.addWidget(self.kullaniciAdiLne)
        self.sifreLne = QtWidgets.QLineEdit(self.layoutWidget)
        self.sifreLne.setEchoMode(QtWidgets.QLineEdit.Password)
        self.sifreLne.setObjectName("sifreLne")
        self.verticalLayout_2.addWidget(self.sifreLne)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.agirisBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.agirisBtn.setObjectName("agirisBtn")
        self.horizontalLayout_3.addWidget(self.agirisBtn)
        self.tlgirisBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.tlgirisBtn.setObjectName("tlgirisBtn")
        self.horizontalLayout_3.addWidget(self.tlgirisBtn)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.kayitBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.kayitBtn.setObjectName("kayitBtn")
        self.verticalLayout_3.addWidget(self.kayitBtn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.kullaniciAdiLabel.setText(_translate("MainWindow", "Kullanıcı Adı:"))
        self.sifreLabel.setText(_translate("MainWindow", "Şifre:"))
        self.agirisBtn.setText(_translate("MainWindow", "Asistan Girişi"))
        self.tlgirisBtn.setText(_translate("MainWindow", "Takım Lideri Girişi"))
        self.kayitBtn.setText(_translate("MainWindow", "Kayıt Ol"))
