# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CagriListesiMenusu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CagrListesiMenusu(object):
    def setupUi(self, CagrListesiMenusu):
        CagrListesiMenusu.setObjectName("CagrListesiMenusu")
        CagrListesiMenusu.resize(800, 594)
        self.centralwidget = QtWidgets.QWidget(CagrListesiMenusu)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 350, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(620, 350, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(100, 50, 611, 291))
        self.tableWidget.setRowCount(15)
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setDefaultSectionSize(80)
        CagrListesiMenusu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CagrListesiMenusu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        CagrListesiMenusu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CagrListesiMenusu)
        self.statusbar.setObjectName("statusbar")
        CagrListesiMenusu.setStatusBar(self.statusbar)

        self.retranslateUi(CagrListesiMenusu)
        QtCore.QMetaObject.connectSlotsByName(CagrListesiMenusu)

    def retranslateUi(self, CagrListesiMenusu):
        _translate = QtCore.QCoreApplication.translate
        CagrListesiMenusu.setWindowTitle(_translate("CagrListesiMenusu", "MainWindow"))
        self.pushButton.setText(_translate("CagrListesiMenusu", "Geri Dön"))
        self.pushButton_2.setText(_translate("CagrListesiMenusu", "Yeni Çağrı"))
