# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ItirazEtme.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ItirazEtme(object):
    def setupUi(self, ItirazEtme):
        ItirazEtme.setObjectName("ItirazEtme")
        ItirazEtme.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ItirazEtme)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 140, 191, 20))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(320, 140, 258, 229))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        ItirazEtme.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ItirazEtme)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        ItirazEtme.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ItirazEtme)
        self.statusbar.setObjectName("statusbar")
        ItirazEtme.setStatusBar(self.statusbar)

        self.retranslateUi(ItirazEtme)
        QtCore.QMetaObject.connectSlotsByName(ItirazEtme)

    def retranslateUi(self, ItirazEtme):
        _translate = QtCore.QCoreApplication.translate
        ItirazEtme.setWindowTitle(_translate("ItirazEtme", "MainWindow"))
        self.label.setText(_translate("ItirazEtme", "İtiraz Açıklamanızı Giriniz:"))
        self.pushButton.setText(_translate("ItirazEtme", "Gönder"))
