# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ItirazlarListesiMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ItirazlarListesiMenu(object):
    def setupUi(self, ItirazlarListesiMenu):
        ItirazlarListesiMenu.setObjectName("ItirazlarListesiMenu")
        ItirazlarListesiMenu.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ItirazlarListesiMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(180, 90, 431, 241))
        self.tableWidget.setRowCount(15)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        ItirazlarListesiMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ItirazlarListesiMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        ItirazlarListesiMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ItirazlarListesiMenu)
        self.statusbar.setObjectName("statusbar")
        ItirazlarListesiMenu.setStatusBar(self.statusbar)

        self.retranslateUi(ItirazlarListesiMenu)
        QtCore.QMetaObject.connectSlotsByName(ItirazlarListesiMenu)

    def retranslateUi(self, ItirazlarListesiMenu):
        _translate = QtCore.QCoreApplication.translate
        ItirazlarListesiMenu.setWindowTitle(_translate("ItirazlarListesiMenu", "MainWindow"))
