# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kayitsf.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_kayitWindow(object):
    def setupUi(self, kayitWindow):
        kayitWindow.setObjectName("kayitWindow")
        kayitWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(kayitWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 90, 225, 123))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.kayitKullaniciAdiLabel = QtWidgets.QLabel(self.layoutWidget)
        self.kayitKullaniciAdiLabel.setObjectName("kayitKullaniciAdiLabel")
        self.verticalLayout.addWidget(self.kayitKullaniciAdiLabel)
        self.kayitSifreLabel = QtWidgets.QLabel(self.layoutWidget)
        self.kayitSifreLabel.setObjectName("kayitSifreLabel")
        self.verticalLayout.addWidget(self.kayitSifreLabel)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.kayitKullaniciAdiLne = QtWidgets.QLineEdit(self.layoutWidget)
        self.kayitKullaniciAdiLne.setObjectName("kayitKullaniciAdiLne")
        self.verticalLayout_2.addWidget(self.kayitKullaniciAdiLne)
        self.kayitSifreLne = QtWidgets.QLineEdit(self.layoutWidget)
        self.kayitSifreLne.setObjectName("kayitSifreLne")
        self.verticalLayout_2.addWidget(self.kayitSifreLne)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.akayitBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.akayitBtn.setAutoDefault(True)
        self.akayitBtn.setFlat(False)
        self.akayitBtn.setObjectName("akayitBtn")
        self.horizontalLayout_2.addWidget(self.akayitBtn)
        self.tlKayitBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.tlKayitBtn.setObjectName("tlKayitBtn")
        self.horizontalLayout_2.addWidget(self.tlKayitBtn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.geriDonBtn = QtWidgets.QPushButton(self.centralwidget)
        self.geriDonBtn.setGeometry(QtCore.QRect(120, 220, 93, 28))
        self.geriDonBtn.setObjectName("geriDonBtn")
        kayitWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(kayitWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        kayitWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(kayitWindow)
        self.statusbar.setObjectName("statusbar")
        kayitWindow.setStatusBar(self.statusbar)

        self.retranslateUi(kayitWindow)
        QtCore.QMetaObject.connectSlotsByName(kayitWindow)

    def retranslateUi(self, kayitWindow):
        _translate = QtCore.QCoreApplication.translate
        kayitWindow.setWindowTitle(_translate("kayitWindow", "MainWindow"))
        self.kayitKullaniciAdiLabel.setText(_translate("kayitWindow", "Kullanıcı Adı:"))
        self.kayitSifreLabel.setText(_translate("kayitWindow", "Şifre:"))
        self.akayitBtn.setText(_translate("kayitWindow", "Asistan Kayıt"))
        self.tlKayitBtn.setText(_translate("kayitWindow", "Takım Lideri Kayıt"))
        self.geriDonBtn.setText(_translate("kayitWindow", "Geri Dön"))
