# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PrimListesiMenusu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PrimListesiMenusu(object):
    def setupUi(self, PrimListesiMenusu):
        PrimListesiMenusu.setObjectName("PrimListesiMenusu")
        PrimListesiMenusu.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(PrimListesiMenusu)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(420, 350, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 350, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(200, 40, 311, 301))
        self.tableWidget.setRowCount(12)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        PrimListesiMenusu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PrimListesiMenusu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        PrimListesiMenusu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PrimListesiMenusu)
        self.statusbar.setObjectName("statusbar")
        PrimListesiMenusu.setStatusBar(self.statusbar)

        self.retranslateUi(PrimListesiMenusu)
        QtCore.QMetaObject.connectSlotsByName(PrimListesiMenusu)

    def retranslateUi(self, PrimListesiMenusu):
        _translate = QtCore.QCoreApplication.translate
        PrimListesiMenusu.setWindowTitle(_translate("PrimListesiMenusu", "MainWindow"))
        self.pushButton.setText(_translate("PrimListesiMenusu", "İtiraz Et"))
        self.pushButton_2.setText(_translate("PrimListesiMenusu", "Geri Dön"))
