# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sifremiunuttum.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SifremiUnuttum(object):
    def setupUi(self, SifremiUnuttum):
        SifremiUnuttum.setObjectName("SifremiUnuttum")
        SifremiUnuttum.resize(811, 600)
        self.centralwidget = QtWidgets.QWidget(SifremiUnuttum)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 140, 111, 16))
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(250, 140, 139, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.epostaLne = QtWidgets.QLineEdit(self.layoutWidget)
        self.epostaLne.setObjectName("epostaLne")
        self.verticalLayout.addWidget(self.epostaLne)
        self.kodYollaBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.kodYollaBtn.setObjectName("kodYollaBtn")
        self.verticalLayout.addWidget(self.kodYollaBtn)
        self.geriDonBtn = QtWidgets.QPushButton(self.centralwidget)
        self.geriDonBtn.setGeometry(QtCore.QRect(150, 170, 93, 28))
        self.geriDonBtn.setObjectName("geriDonBtn")
        SifremiUnuttum.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SifremiUnuttum)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 811, 26))
        self.menubar.setObjectName("menubar")
        SifremiUnuttum.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SifremiUnuttum)
        self.statusbar.setObjectName("statusbar")
        SifremiUnuttum.setStatusBar(self.statusbar)

        self.retranslateUi(SifremiUnuttum)
        QtCore.QMetaObject.connectSlotsByName(SifremiUnuttum)

    def retranslateUi(self, SifremiUnuttum):
        _translate = QtCore.QCoreApplication.translate
        SifremiUnuttum.setWindowTitle(_translate("SifremiUnuttum", "Şifremi Unuttum"))
        self.label.setText(_translate("SifremiUnuttum", "E-Postanızı Giriniz:"))
        self.kodYollaBtn.setText(_translate("SifremiUnuttum", "Tamam"))
        self.geriDonBtn.setText(_translate("SifremiUnuttum", "Geri Dön"))
