# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TLItirazCevaplama.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TLItirazCevaplama(object):
    def setupUi(self, TLItirazCevaplama):
        TLItirazCevaplama.setObjectName("TLItirazCevaplama")
        TLItirazCevaplama.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(TLItirazCevaplama)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 140, 171, 21))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(280, 140, 258, 229))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        TLItirazCevaplama.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TLItirazCevaplama)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        TLItirazCevaplama.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TLItirazCevaplama)
        self.statusbar.setObjectName("statusbar")
        TLItirazCevaplama.setStatusBar(self.statusbar)

        self.retranslateUi(TLItirazCevaplama)
        QtCore.QMetaObject.connectSlotsByName(TLItirazCevaplama)

    def retranslateUi(self, TLItirazCevaplama):
        _translate = QtCore.QCoreApplication.translate
        TLItirazCevaplama.setWindowTitle(_translate("TLItirazCevaplama", "MainWindow"))
        self.label.setText(_translate("TLItirazCevaplama", "İtiraz Açıklaması:"))
        self.pushButton.setText(_translate("TLItirazCevaplama", "Gönder"))
