# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TLYapilanItirazlar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TLYapilanItirazlar(object):
    def setupUi(self, TLYapilanItirazlar):
        TLYapilanItirazlar.setObjectName("TLYapilanItirazlar")
        TLYapilanItirazlar.resize(836, 600)
        self.centralwidget = QtWidgets.QWidget(TLYapilanItirazlar)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 80, 781, 281))
        self.tableWidget.setRowCount(25)
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        TLYapilanItirazlar.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TLYapilanItirazlar)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 836, 26))
        self.menubar.setObjectName("menubar")
        TLYapilanItirazlar.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TLYapilanItirazlar)
        self.statusbar.setObjectName("statusbar")
        TLYapilanItirazlar.setStatusBar(self.statusbar)

        self.retranslateUi(TLYapilanItirazlar)
        QtCore.QMetaObject.connectSlotsByName(TLYapilanItirazlar)

    def retranslateUi(self, TLYapilanItirazlar):
        _translate = QtCore.QCoreApplication.translate
        TLYapilanItirazlar.setWindowTitle(_translate("TLYapilanItirazlar", "MainWindow"))
